# Generated by Django 6.0.5 on 2026-06-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('yield_percentage', models.FloatField()),
                ('defects', models.IntegerField(default=0)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionline')),
            ],
        ),
    ]
