# Generated by Django 6.0.5 on 2026-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='output',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='yield_percentage',
            field=models.FloatField(default=0),
        ),
    ]
