# Generated by Django 6.0.5 on 2026-06-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('total_units', models.IntegerField()),
                ('good_units', models.IntegerField()),
                ('defective_units', models.IntegerField()),
                ('yield_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productionline')),
            ],
        ),
    ]
