# Generated by Django 6.0.5 on 2026-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldrecord',
            name='defective_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='good_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yieldrecord',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
